### PR TITLE
"simple" conditional logic support

### PR DESCRIPTION
**Pull request by zapnap**
Adds a matcher to the base set. Super simple / preliminary support for conditional logic. Really just truthiness. No support for comparison operators yet (we don't need them at this point...)

Thoughts? Let me know if you think this is good to merge and/or release an updated gem.

### CODE REVIEW

**Comment by markbates** [comment]
Looks good to me. Feel free and merge and release.

**Comment by zapnap** [comment]
I was almost wondering if we should call it something other than 'if' since it only works for the simplest 'existence' type use cases, rather than all conditionals / comparisons...

**Comment by markbates** [comment]
What are thinking if not if?
—
Mark Bates

**Comment by zapnap** [comment]
Don't really have any brilliant ideas. I guess that's why handlebars does the {{#stuff}} syntax, because it isn't really a proper conditional. But I don't love that either _shrug_

**Comment by sbeam** [comment]
what about "exists"?

**Comment by markbates** [comment]
I'm ok with 'if' I can see it expanding to involve more complex statements, such as:

{{ if 1 is 1 }}

{{/if}}

etc…

---

Mark Bates
Subscribe to my Screen Casts:
http://www.metacasts.tv (coupon: MARKSEMAIL1)

Buy my Books!
http://books.markbates.com
Programming in CoffeeScript (2012)
Distributed Programming in Ruby (2009)

**Pull request merged**
