### PR TITLE
re-organize handlers

### PR DESCRIPTION
**Pull request by zapnap**
This should make it easier to extend / change the base handlers in other projects. Thoughts?

### CODE REVIEW

**Comment by markbates** [comment]
I like it. It really cleans things up. My only comment would be if you could split the handlers out into their own files. I generally try not to nest multiple classes in one file, unless they're 'private' classes. Other than that, feel free and merge it in and release it.

**Comment by zapnap** [comment]
Good call. Will update shortly.

**Comment by zapnap** [comment]
Alright, I think that makes more sense. I'll merge it in.

**Comment by zapnap** [comment]
Patch release or minor version bump? :dancers:

**Comment by markbates** [comment]
i think it's big enough to warrant a minor version bump

**Pull request closed without merging**
